import jsPDF from 'jspdf';

export const generateFireReport = (data, fireNumbers, mode = 'income') => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // -- HEADER --
    doc.setFillColor(30, 41, 59); // Slate 800
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text("FIRE Freedom Plan", 20, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${date}`, 20, 30);
    doc.text("Every reality begins as a dream.", 140, 28);

    // -- SECTION 1: Inputs --
    doc.setTextColor(50);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text("1. Your Inputs", 20, 60);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(80);

    const inputData = [
        `Return Rate Assumption: ${data.investmentReturnRate}%`,
        `Inflation Assumption: ${data.inflationRate}%`,
        `Current Corpus: Rs. ${(data.currentCorpus / 100000).toFixed(2)} L`
    ];

    if (mode === 'income') {
        inputData.unshift(`Annual Income: Rs. ${(data.annualIncome / 100000).toFixed(2)} L`);
        inputData.splice(1, 0, `Annual Expenses: Rs. ${(data.annualExpenses / 100000).toFixed(2)} L`);
    } else {
        inputData.unshift(`Dream Target: Rs. ${(data.targetCorpus / 10000000).toFixed(2)} Cr`);
        inputData.splice(1, 0, `Timeline: ${data.yearsToRetire} Years`);
    }

    let y = 70;
    inputData.forEach(text => {
        doc.text(`• ${text}`, 25, y);
        y += 8;
    });

    // -- SECTION 2: The Numbers --
    y += 10;
    doc.setTextColor(50);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text("2. The Strategy", 20, y);
    y += 10;

    // Summary Box
    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(20, y, 170, 40, 'F');
    doc.setTextColor(30);
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    let summaryText = "";
    if (mode === 'income') {
        const savings = data.annualIncome - data.annualExpenses;
        summaryText = `With your current savings of Rs. ${(savings / 100000).toFixed(2)}L per year, you are on track to hit Traditional FIRE in ${data.yearsToRetire || 'X'} years. Increasing your savings rate is the #1 lever to pull.`;
    } else {
        // rough calc for report text
        summaryText = "To reach your Dream Target, you'll need to aggressively save and invest. Focus on increasing income streams while keeping lifestyle inflation in check.";
    }

    // Split text to fit
    const splitText = doc.splitTextToSize(summaryText, 160);
    doc.text(splitText, 25, y + 10);

    // -- SECTION 3: FIRE Types (Table) --
    if (mode === 'income') {
        y += 50;
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(50);
        doc.text("3. FIRE Benchmarks", 20, y);
        y += 10;

        const headers = ["Type", "Corpus Needed", "Status"];
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(headers[0], 25, y);
        doc.text(headers[1], 80, y);
        doc.text(headers[2], 140, y);

        y += 5;
        doc.setLineWidth(0.5);
        doc.line(20, y, 190, y);
        y += 10;

        doc.setTextColor(50);
        doc.setFontSize(11);

        // All 6 FIRE Types
        const types = [
            { name: "Coast FIRE", val: fireNumbers.coast, desc: "Invest now, relax later" },
            { name: "Barista FIRE", val: fireNumbers.barista, desc: "Part-time work covers expenses" },
            { name: "Lean FIRE", val: fireNumbers.lean, desc: "Minimalist living" },
            { name: "Traditional", val: fireNumbers.traditional, desc: "Standard retirement" },
            { name: "Slow FIRE", val: fireNumbers.slow, desc: "Enjoying the journey" },
            { name: "Fat FIRE", val: fireNumbers.fat, desc: "Luxury retirement" },
        ];

        types.forEach(t => {
            const val = t.val || 0;
            doc.text(t.name, 25, y);
            doc.text(`Rs. ${(val / 10000000).toFixed(2)} Cr`, 80, y);
            doc.text("In Progress", 140, y); // Dynamic years calc hard in simple pdf gen without importing helper, simplified.
            y += 10;
        });
    }

    // -- FOOTER --
    doc.setTextColor(150);
    doc.setFontSize(9);
    doc.text("Generated by FIRE Tracker. Not financial advice.", 105, 280, { align: 'center' });

    doc.save("FIRE_Freedom_Plan.pdf");
};
